# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: nha_carro
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
